### ISSUE TITLE
Is there an existing firmware for the rerouted arisu?

### ISSUE THREAD

**Issue by DeskDaily** [itsnoteasy/misc#1]
Is there an existing firmware for the rerouted arisu?

**Comment by itsnoteasy** [comment]
there wasn't because nobody built it but the only difference was some pin changes. here's how you do it.
grab the arisu firmware here: https://github.com/FateNozomi/qmk_firmware/tree/master/keyboards/arisu
then edit config.h to these lines
//arisu_rerouted
#define MATRIX_ROW_PINS { D0, D5, D3, D2, D1 }
#define MATRIX_COL_PINS { C6, B6, C7, E6, F0, F1, D4, B7, B3, B1, B5, B4, D7, D6, B0 }
I just read these off the schematic so there may be errors but it's probably ok.

**Comment by DeskDaily** [comment]
Hi! I made some of those and I actually made firmware for it and made it work. I am just wondering what's the process of merging the firmware to the qmk main repo since it is not the original version.

**Comment by itsnoteasy** [comment]
I don't think you should submit it to the main repo since it is an incompatible fork. It would confuse other users. If there's any compatible code improvements then do a fork and pull request. If you would like I could re-upload the zip with qmk code included.

**Comment by DeskDaily** [comment]
What do you mean it's an incompatible fork? Sorry, I am new to this thing.

Do you think I can add it to my own folder under qmk? I made some pcbs and I will put it all under keyboards/nightly_boards. Then I can put the link of the gerber files so people will also know that it is your version.

That way, it's still separate from the original arisu firmware. I can create a new branch on my own fork of qmk so that you can see the firmware that I made.

**Comment by itsnoteasy** [comment]
There were some minor design flaws with the arisu so I changed the pinout to the mcu as an experiment. I use github as a way of backing up important files as well as a way to avoid others reinventing the wheel and doing the same work.
The changed pinout makes it incompatible with the stock firmware. That's why I advertised the arisu.zip file only on reddit.

There is little advantage to publicizing the experimental design by uploading it to the qmk repo. If you wanted to sell pcbs the arisu.zip file would be perfectly sufficient as a base. It changes the usb port to mini usb and moves some problematic vias out from underneath the mcu while retaining backwards compatibility.

I would upload the arisu_rerouted firmware to the zip if I knew that it was tested as working. If you would like you could upload your config.h to a pastebin.com instance and I'll do the rest.
